language: node_js
node_js:
  - 13

branches:
  only:
    - main

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Print the version for logging
  - docker --version
  # Build and tag feed-api
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed vanlinh303/udagram-api-feed:v4
  # Build and tag user-api
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user vanlinh303/udagram-api-user:v4
  # Build and tag frontend-api
  - docker build -t udagram-frontend:local ./udagram-frontend
  - docker tag udagram-frontend:local vanlinh303/udagram-frontend:v11
  # Build and tag reverseproxy-api
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy vanlinh303/reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vanlinh303/udagram-api-feed:v4
  - docker push vanlinh303/udagram-api-user:v4
  - docker push vanlinh303/udagram-frontend:v11
  - docker push vanlinh303/reverseproxy:v4
