version: 2.1
jobs:
  build-images:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker --version
            docker build --no-cache -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed vanlinh303/udagram-api-feed:v4
            docker build --no-cache -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user vanlinh303/udagram-api-user:v4
            docker build --no-cache -t udagram-frontend:local ./udagram-frontend
            docker tag udagram-frontend:local vanlinh303/udagram-frontend:v11
            docker build --no-cache -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy vanlinh303/reverseproxy:v4
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - /var/lib/docker
  push-images:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: push images
          command: |
            docker --version
            docker images  # Double-check if images exist with correct tags
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push vanlinh303/udagram-api-feed:v4
            docker push vanlinh303/udagram-api-user:v4
            docker push vanlinh303/udagram-frontend:v11
            docker push vanlinh303/reverseproxy:v4
workflows:
  default:
    jobs:
      - build-images
      - push-images:
          requires: [build-images]
